etl:
  postgres:
    dsn:
      dbname: movies_database
      user: movies_db_admin
      password: tester100
      host: database
      port: 5432
      options: "-c search_path=content"
      limit: 100

  es:
    default_host:
      host: es01
      port: 9200
    index_name: movies
    index_config: "index_config.json"

  state_file_name: "state.yaml"
  fetch_delay: 0.1
  log_status_period: 180

logger:
  version: 1
  disable_existing_loggers: true

  handlers:
    console:
      class: logging.StreamHandler
      formatter: brief
      level: INFO
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: default
      level: INFO
      maxBytes: 10485760 # 10MB
      backupCount: 5
      encoding: utf8
    file_error:
      class: logging.handlers.RotatingFileHandler
      formatter: error
      level: ERROR
      maxBytes: 10485760 # 10MB
      backupCount: 5
      encoding: utf8

  formatters:
    brief:
      format: '%(message)s'
    default:
      format: '%(asctime)s %(levelname)s %(name)s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
    error:
      format: "!!!%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s()"

  loggers:
      __main__:
        level: INFO
        handlers: [console, file, file_error]